### ISSUE TITLE
Unable to uninstall .NET SDK 5.0.100-preview.3.20216.6 (x86) via dotnet-core-uninstall

### ISSUE THREAD

**Issue by Anna-Guseva** [dotnet/cli-lab#215]
```
C:\WINDOWS\system32>dotnet-core-uninstall remove --all-previews --sdk
The following items will be removed:
  Microsoft .NET SDK 5.0.100-preview.3.20216.6 (x86)
  Microsoft .NET Core SDK 2.1.800 - preview (x64)
  Microsoft .NET Core SDK 2.1.700 - preview (x64)

To avoid breaking Visual Studio or other problems, read https://aka.ms/dotnet-core-uninstall-docs.

Do you want to continue? [y/n] y
Uninstalling: Microsoft .NET SDK 5.0.100-preview.3.20216.6 (x86).
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Tools.Uninstall.Shared.Commands.UninstallCommandExec.DoIt(IEnumerable`1 bundles)
   at Microsoft.DotNet.Tools.Uninstall.Shared.Commands.UninstallCommandExec.Execute(IBundleCollector bundleCollector)
   at Microsoft.DotNet.Tools.Uninstall.Shared.Configs.CommandLineConfigs.<>c__DisplayClass40_0.<.cctor>b__6()
   at Microsoft.DotNet.Tools.Uninstall.Shared.Exceptions.ExceptionHandler.<>c__DisplayClass0_0.<HandleException>b__0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

**Comment by sfoslund** [comment]
@Anna-Guseva is this error only showing up with the x86 bundle? Based on the stack trace it looks like something is wrong with the uninstall command we pulled from the registry. Can you search your registry for `Microsoft .NET SDK 5.0.100-preview.3.20216.6 (x86)` and tell me what shows up in the UninstallString key? You can search in the [registry editor](https://support.microsoft.com/en-us/windows/how-to-open-registry-editor-in-windows-10-deab38e6-91d6-e0aa-4b7c-8878d9e07b11) and it should look something like this (except the version you're trying to uninstall instead of 5.0.402): 

![Uninstall string registry](https://user-images.githubusercontent.com/16010855/141155434-3aa82738-9748-4d5e-825d-606f86439521.png)

**Comment by Anna-Guseva** [comment]
Here is UninstallString path:

![image](https://user-images.githubusercontent.com/14165151/141660461-f7832c4e-201f-4992-a101-558a17d3cc0e.png)

I've checked this path and it looks like the specified folder is missing on disk. Probably this is the reason for the  exception in dotnet-core-uninstall.

**Comment by sfoslund** [comment]
Yeah, makes sense. Do you know how that dir could have been removed? Have you edited anything in there by hand?

**Comment by Anna-Guseva** [comment]
I don't remember it, sorry. I do not exclude the possibility that these files could have been removed by hand.

**Comment by sfoslund** [comment]
No problem. I've never seen this particular error before and I'm not sure how else that file could have been removed, so unless we get more reports of this or a repo, I'm going to close this issue.
